INSERT INTO lettuce_currency (currency_code, full_name) VALUES('USD', 'United States dollar');
INSERT INTO lettuce_currency (currency_code, full_name) VALUES('EUR', 'Euro');
INSERT INTO lettuce_currency (currency_code, full_name) VALUES('JPY', 'Japanese yen');
INSERT INTO lettuce_currency (currency_code, full_name) VALUES('GBP', 'Pound sterling');
INSERT INTO lettuce_currency (currency_code, full_name) VALUES('AUD', 'Australian dollar');
INSERT INTO lettuce_currency (currency_code, full_name) VALUES('CAD', 'Canadian dollar');
INSERT INTO lettuce_currency (currency_code, full_name) VALUES('CHF', 'Swiss franc');
INSERT INTO lettuce_currency (currency_code, full_name) VALUES('CNY', 'Chinese yuan');
INSERT INTO lettuce_currency (currency_code, full_name) VALUES('HKD', 'Hong Kong dollar');
INSERT INTO lettuce_currency (currency_code, full_name) VALUES('NZD', 'New Zealand dollar');